# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "9b1d7e0a98c144b92d7a27129cb49082"
name = "clp"
handle = "clp"
application_url = "https://floors-compromise-correct-patricia.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "mananiyo.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://floors-compromise-correct-patricia.trycloudflare.com/auth/callback",
  "https://floors-compromise-correct-patricia.trycloudflare.com/auth/shopify/callback",
  "https://floors-compromise-correct-patricia.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
